version: '3'
networks:
    etcd:
    kube-api:
services:
    etcd:
        image: "quay.io/coreos/etcd:v3.2"
        networks:
            - etcd
        command:
            - etcd
            - --name=etcd0
            - --advertise-client-urls=http://etcd:2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --initial-advertise-peer-urls=http://etcd:2380
            - --initial-cluster-state=new
        ports:
            - 2379:2379
        healthcheck:
            test:
                - CMD-SHELL
                - wget -qO- http://127.0.0.1:2379/health || exit 1 
    kube-apiserver:
        depends_on:
            - etcd
        image: "quay.io/coreos/hyperkube:${KUBERNETES_VERSION}_coreos.0"
        networks:
            - etcd
            - kube-api
        command:
            - kube-apiserver
            - --etcd-servers=http://etcd:2379
            - --insecure_bind_address=0.0.0.0
            - --insecure_port=8080
            - --service-cluster-ip-range=10.244.0.0/16
            - --allow-privileged=true
        ports:
            - 8080:8080
    kubelet:
        depends_on:
            - kube-apiserver
        image: "quay.io/coreos/hyperkube:${KUBERNETES_VERSION}_coreos.0"
        privileged: true
        networks:
            - kube-api
        volumes:
            - /:/rootfs:ro 
            - /sys:/sys:ro
            - /var/run:/var/run:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /var/lib/docker/:/var/lib/docker:rw
            - /proc/:/rootfs/proc/
        command:
            - kubelet
            - --v=2
            - --address=0.0.0.0
            - --enable-server
            - --api-servers=http://kube-apiserver:8080
            - --port=10250
            - --cluster-domain=cluster.local
            - --cluster-dns=8.8.8.8
            - --allow-privileged=true
    kube-controller-manager:
        depends_on:
            - kube-apiserver
        image: "quay.io/coreos/hyperkube:${KUBERNETES_VERSION}_coreos.0"
        networks:
            - kube-api
        command:
            - kube-controller-manager
            - --master=http://kube-apiserver:8080
    kube-scheduler:
        image: "quay.io/coreos/hyperkube:${KUBERNETES_VERSION}_coreos.0"
        networks:
            - kube-api
        command:
            - kube-scheduler
            - --master=http://kube-apiserver:8080
    kube-proxy:
        image: "quay.io/coreos/hyperkube:${KUBERNETES_VERSION}_coreos.0"
        network_mode: host
        privileged: true
        command:
            - kube-proxy
            - --master=http://localhost:8080
            - --proxy-mode=userspace